# Generated by Django 3.1.7 on 2021-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('PosttId', models.AutoField(primary_key=True, serialize=False)),
                ('MainHeading', models.CharField(max_length=500)),
                ('MainDes', models.CharField(max_length=10000)),
                ('SubHeading1', models.CharField(default='', max_length=100)),
                ('SubDes1', models.CharField(default='', max_length=500)),
                ('SubHeading2', models.CharField(default='', max_length=100)),
                ('SubDes2', models.CharField(default='', max_length=500)),
                ('PostDate', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='blog')),
            ],
        ),
    ]
