# Generated by Django 3.2 on 2021-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('Usrid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='', max_length=150)),
                ('age', models.IntegerField(default='')),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
